Repository wecode-bootcamp-korea/29-1st-JU-LABO-backend, pull requests merged in 2022-02, with the labels that each got.

#4 [29기 김지연] 상품 상세 페이지 API 작업
  julabo/settings.py
  julabo/urls.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#9 [29기 최형택] users 수정
  categories/views.py
  julabo/settings.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#11 [29기 최형택] 데코레이터 추가
  julabo/settings.py
  users/utils.py
Labels: Status: 리뷰 요청

#14 [29기 최창현] 제품 조회
  products/migrations/0001_initial.py
  users/migrations/0002_userproduct.py
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#10 [29기 김지연] 장바구니 기능 구현
  carts/__init__.py
  carts/admin.py
  carts/apps.py
  carts/models.py
  carts/tests.py
  carts/urls.py
  carts/views.py
  categories/urls.py
  categories/views.py
  julabo/settings.py
  julabo/urls.py
  products/models.py
  products/urls.py
  products/views.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#15 29기 최형택 [fix] login
  categories/urls.py
  categories/views.py
  users/views.py
Labels: Status: 리뷰 요청

#12 [29기 김지연] 상품 정보 인덱스 삽입 순서 수정
  products/urls.py
  products/views.py
Labels: Status: 수정 요청, Status: Conflict 해결 요청

#16 [29기 김지연] 상품 검색 및 상위 검색어 반환 기능 추가
  julabo/settings.py
  products/views.py
  users/views.py
Labels: Status: 리뷰 요청
